## Basic Configuration
baseurl = "http://arloor.com"
languageCode = "zh-CN"
hasCJKLanguage = true

title = "ARLOOR"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
#googleAnalytics = "UA-133187648-1"
#enableRobotsTXT = true

summarylength = 160

paginate = 10

## Site Settings
[params]
# 取消注释以开启评论
#UtterancesRepo= "arloor/blog"
UtterancesIssueTerm = "pathname"
UtterancesTheme="github-light"


    layoutReverse = false
    author = "刘港欢"
    title = "刘港欢"
    description = "私人小破站"
    authorimage = "/img/head.jpeg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "arloor"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"
    toc="hugo"

[params.meta]
    keywords="刘港欢,  arloor, moontell"
    description = "刘港欢的博客——专注java、go与网络编程"

## Social Accounts
[params.social]
    github = "arloor"
    #instagram = "<username>"
    #xing = "<username>"
    #linkedin = "<username>"
    twitter = "njulgh"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    telegram = "popstary"
    email = "admin@arloor.com"
    #gravatar = "admin@arloor.com"

## Main Menu
[[menu.main]]
    name = "文章"
    weight = 10
    identifier = "文章"
    url = "/posts/"
[[menu.main]]
    name = "分类"
    weight = 100
    identifier = "分类"
    url = "/categories/"
[[menu.main]]
    name = "标签"
    weight = 1000
    identifier = "标签"
    url = "/tags/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 1001
    url = "/about/"
